### ISSUE TITLE
Feature request: Remember last selected link after having visited website.

### ISSUE THREAD

**Issue by FedeCuci** [jchafik/google-search-shortcuts#18] opened 2020-10-08 11:58 UTC
After having visited a website through the extension and go back to the search results, and press TAB to keep navigating, the extension always goes back to the first result. That means that I have to go down again and again the whole time to visit the next link, which is kind of annoying. It would be nice if the extension remembered the link you just visited so that when you come back the highlighted link is the one you just were so that when you press TAB you go directly to the next one.

**Comment by jchafik** [comment] 2022-03-27 03:22
Closing as duplicate of #14

**Closed as completed by jchafik** 2022-03-27 03:22 UTC
Labels: duplicate
