### ISSUE TITLE
Settings do not work in Firefox 57

### ISSUE THREAD

**Issue by xnick** [jchafik/google-search-shortcuts#5] opened 2017-11-17 18:51 UTC
Settings cannot be saved in firefox 57. 

Also it defaults to everything being unchecked, leaving the extension basically disabled.

The error from the debug log:
```
extOptions is undefined  options.js:14
	loadFormOptions moz-extension://2ac91781-abf4-400a-8e69-9200efaa5a42/js/options.js:14:5
	<anonymous> moz-extension://2ac91781-abf4-400a-8e69-9200efaa5a42/js/options.js:47:5
	apply self-hosted:4154:5
	applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:283:16
	wrapPromise/</< resource://gre/modules/ExtensionCommon.jsm:466:15
	withLastError resource://gre/modules/ExtensionCommon.jsm:404:14
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:460:11
```

Weirdly, if I extract the xpi and load it from "source" with web-ext run, it works just fine. Not the git version, the package from the firefox...
It does not work though if I load it from inside firefox.

**Comment by jchafik** [comment] 2017-11-17 23:19
I'm unable to reproduce. Can you give me any more details? i.e., did you recently upgrade? from what version? What O.S. are you running on? etc..

The settings page is pretty simple. If you want to compile from this repository, you'll have to apply manifest.firefox.patch first.

**Comment by xnick** [comment] 2017-11-18 00:44
I'm gonna go on limb and say that it's probably a Firefox issue.

Anyway, browser is Firefox 57.0 64bit, OS is Arch Linux. I just moved to Firefox, so new installation of both it and your extension. (I was on Chrome previously)
Just checked on another of my machines (again Arch Linux and Firefox 57.0) and it has no issues with it. 

On the problematic machine, both the git versions and the extracted .xpi work just fine when loaded with web-ext. The issue is when I install from within Firefox; either through the AMO, or loading the unpackaged extension through debug.

There shouldn't be anything radically different between the machines wrt libraries, etc. Obviously they are completely different machines, but I don't see how that would affect a browser extention...

So feel free to close this issue if you want. I doubt the problem is in your code.

**Comment by jchafik** [comment] 2017-11-19 21:34
I'll close this for now and reopen if I start to see other complaints. Thank you for reaching out!

**Closed as completed by jchafik** 2017-11-19 21:34 UTC
